- name: Входим в домен  
  ansible.windows.win_domain_membership:  
    dns_domain_name: "{{ domain_name }}"  
    domain_admin_user: "{{ domain_admin_user }}"  
    domain_admin_password: "{{ domain_admin_password }}"  
    hostname: "{{ ansible_hostname }}"  
    domain_ou_path: "{{ win_domain_ou }}"  
    state: domain  
  register: domain_join  

- name: Перезагружаем, если нужно  
  ansible.windows.win_reboot:  
    when: domain_join.reboot_required  